apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ismeroppfolging
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
        - application: syfooversiktsrv
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "dokarkiv.prod-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
        - application: syfobehandlendeenhet
        - application: isoppfolgingstilfelle
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: syfooppdfgen
          namespace: team-esyfo
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: ismeroppfolging-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: KTOR_ENV
      value: "production"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: ESYFO_PDFGEN_CLIENT_ID
      value: "prod-gcp.team-esyfo.syfooppdfgen"
    - name: ESYFO_PDFGEN_URL
      value: "http://syfooppdfgen.team-esyfo"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: VEILARBVEDTAKSSTOTTE_CLIENT_ID
      value: "prod-gcp.obo.veilarbvedtaksstotte"
    - name: VEILARBVEDTAKSSTOTTE_URL
      value: "http://veilarbvedtaksstotte.obo"
    - name: DOKARKIV_CLIENT_ID
      value: "prod-fss.teamdokumenthandtering.dokarkiv"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: "http://isoppfolgingstilfelle"
    - name: IS_SVAR_TOPIC_ENABLED
      value: "false"
    - name: IS_JOURNALFORING_RETRY_ENABLED
      value: "true"
    - name: IS_KANDIDAT_PUBLISHING_ENABLED
      value: "false"
