ALTER TABLE SEN_OPPFOLGING_KANDIDAT
    ADD COLUMN varsel_id CHAR(36) DEFAULT NULL;

ALTER TABLE SEN_OPPFOLGING_KANDIDAT
    ALTER COLUMN varsel_at DROP NOT NULL;

CREATE INDEX IX_SEN_OPPFOLGING_KANDIDAT_VARSEL_ID on SEN_OPPFOLGING_KANDIDAT (varsel_id);
