CREATE TABLE KARTLEGGINGSSPORSMAL_KANDIDAT_STATUSENDRING
(
    id           SERIAL PRIMARY KEY,
    uuid         CHAR(36)    NOT NULL UNIQUE,
    kandidat_id  INTEGER REFERENCES KARTLEGGINGSSPORSMAL_KANDIDAT (id) ON DELETE CASCADE,
    created_at   timestamptz NOT NULL,
    status       VARCHAR(20) NOT NULL,
    published_at timestamptz
);

CREATE INDEX IX_KARTLEGGINGSSPORSMAL_KANDIDAT_STATUSENDRING_ID on KARTLEGGINGSSPORSMAL_KANDIDAT_STATUSENDRING (kandidat_id);
