ALTER TABLE KARTLEGGINGSSPORSMAL_KANDIDAT
    ADD COLUMN updated_at TIMESTAMPTZ;

UPDATE KARTLEGGINGSSPORSMAL_KANDIDAT
SET updated_at = created_at;

ALTER TABLE KARTLEGGINGSSPORSMAL_KANDIDAT
    ALTER COLUMN updated_at SET NOT NULL;
