ALTER TABLE KARTLEGGINGSSPORSMAL_KANDIDAT
    ADD COLUMN should_send_varsel BOOLEAN NOT NULL DEFAULT false;

UPDATE KARTLEGGINGSSPORSMAL_KANDIDAT
SET should_send_varsel = true
WHERE varslet_at IS NOT NULL;
